[global]
showWarningOnDirectExecution = false

[logger]
level = "error"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
primaryColor = "#FF8310"
backgroundColor = "#f0f0f0"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
